version: '3.8'

services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
      - "1514:1514/tcp"
      - "1514:1514/udp"
    volumes:
      - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./logs:/var/log
    restart: always

  postgres:
    image: postgres:15
    container_name: security-postgres
    environment:
      POSTGRES_DB: security_monitoring
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d security_monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: security-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Equipobot_red2
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=security_monitoring
      - DB_POSTGRESDB_USER=db_user
      - DB_POSTGRESDB_PASSWORD=db_pass
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./logs:/home/node/logs:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data: